import { IsString, IsNotEmpty, MaxLength, Matches } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class SendMessageDto {
  @ApiProperty({ description: 'UUID session token generated by the client' })
  @IsString()
  @IsNotEmpty()
  @Matches(/^[0-9a-zA-Z_-]{8,64}$/, { message: 'Invalid session token format' })
  sessionToken: string;

  @ApiProperty({ description: 'User message text' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(2000)
  message: string;
}
